### ISSUE TITLE
[TODO][BUG] Fix the sheetmetalcalc.py

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/learn_python#2]
Having a hard time trying to figure out how to calculate a few things:

Say the corner of the first part is at a 1" x 1" margin from the sheet corner, and the parts are 3"x4" with 1 inch between them in row and column.. how many parts would you then get from the 12" x 48" sheet?

I'm reasonably certain the parts coverage calc is inaccurate.

Here is the current output if you run with these numbers.  There is also no implementation of entering values as decimals like 102.75

$ python3.7 sheetmetalcalc.py
Input the length of your sheet in inches: 12
Input the width of your sheet in inches: 48
Input the margin width of your sheet in inches: 1
Input the length of your part in inches: 3
Input the width of your part in inches: 4
Your sheet length is 12 inches
Your sheet width is 48 inches
The area of your sheet is 576.
The area your parts cover across your sheet is 12 square inches.

**Comment by gbowne1** [comment]
@Kempeter That commit did not update the issue so I could pull the commit. can you do a PR so I can review and merge?

**Comment by Kempeter** [comment]
@gbowne1 okay

**Comment by Kempeter** [comment]
@gbowne1 I do not fully understand the problem

**Comment by gbowne1** [comment]
@Kempeter I can make the changes myself but if you would like to submit a change you can do a pull request.

**Comment by gbowne1** [comment]
This program should also tell the users how many sheets of a certain size would be needed to get the number
of parts they require.

**Comment by Kempeter** [comment]
Can you give an example? I don't quite understand.

**Comment by gbowne1** [comment]
@Kempeter to test this, I put in these values.

```shell
Input the length of your sheet in inches: 48
Input the width of your sheet in inches: 144
Input the margin width of your sheet in inches: 1
Input the length of your part in inches: 5
Input the width of your part in inches: 2
The area of your sheet is 6912.
The area your parts cover across your sheet is 10 square inches.
488 pieces can be cut from the sheet. 
The area your parts cover across your sheet is 4880 square inches.
The number of parts that fit on this sheet length in this configuration is 8. 
The number of parts that fit on this sheet width in this configuration is 57. 
```
"The area your parts cover across your sheet is 10 square inches." is wrong.  each part is 10 square inches individually.. but but not for the whole sheet.

as for the total sheet quantity problem say you needed 1197 parts but could only get 57 parts a sheet, it should tell you how many sheets you need to have in order to make the 1197 parts. 

It might also be a good thing to be able to tell if you could not get enough parts out of a single sheet

**Comment by gbowne1** [comment]
I tried to change the margin to 5/8" which is 0.625" with the same sheet size l x w.. this was the output.

$ python3.7 sheetmetalcalc.py
Input the length of your sheet in inches: 48
Input the width of your sheet in inches: 144
Input the margin width of your sheet in inches: .625
Traceback (most recent call last):
  File "sheetmetalcalc.py", line 11, in <module>
    margin = int(input("Input the margin width of your sheet in inches: "))
ValueError: invalid literal for int() with base 10: '.625'

**Comment by gbowne1** [comment]
I also tried to change the part size to 5.75" x 2.25" but keep the 1 margin and the same sheet size.

This was the output there
$ python3.7 sheetmetalcalc.py
Input the length of your sheet in inches: 48
Input the width of your sheet in inches: 144
Input the margin width of your sheet in inches: 1
Input the length of your part in inches: 5.75
Traceback (most recent call last):
  File "sheetmetalcalc.py", line 13, in <module>
    part_len = int(input("Input the length of your part in inches: "))
ValueError: invalid literal for int() with base 10: '5.75'

**Comment by Kempeter** [comment]
This will be good. I rounded the numbers to two decimal places.

**Comment by Kempeter** [comment]
> @Kempeter to test this, I put in these values.
> 
> ```shell
> Input the length of your sheet in inches: 48
> Input the width of your sheet in inches: 144
> Input the margin width of your sheet in inches: 1
> Input the length of your part in inches: 5
> Input the width of your part in inches: 2
> The area of your sheet is 6912.
> The area your parts cover across your sheet is 10 square inches.
> 488 pieces can be cut from the sheet. 
> The area your parts cover across your sheet is 4880 square inches.
> The number of parts that fit on this sheet length in this configuration is 8. 
> The number of parts that fit on this sheet width in this configuration is 57. 
> ```
> 
> "The area your parts cover across your sheet is 10 square inches." is wrong. each part is 10 square inches individually.. but but not for the whole sheet.
> 
> as for the total sheet quantity problem say you needed 1197 parts but could only get 57 parts a sheet, it should tell you how many sheets you need to have in order to make the 1197 parts.
> 
> It might also be a good thing to be able to tell if you could not get enough parts out of a single sheet

i will do this tomorrow

**Comment by gbowne1** [comment]
Ok.

**Comment by gbowne1** [comment]
This is getting added to the machinistcalc program/app.
